sudo: false
language: python

stages:
  - test
  - name: conda_package
    if: tag =~ ^v(\d+|\.)+[^a-z]\d+$
  - name: pypi_package
    if: tag =~ ^v(\d+|\.)+[^a-z]\d+$

jobs:
  include:
  - &default
    stage: test
    python: 3.6
    # TODO
    install: true
    script: true

  - <<: *default
    stage: pypi_package
    install: true
    script: true
    deploy:
      provider: pypi
      distributions: "sdist bdist_wheel"
      on:
        tags: true
      user: ceball
      password:
        secure: VJpGRSoKsuSZSIuBwXmd/XtAviateO7xlU4LYVzz9wrfI1xzd7TQkrRLbL/JQIzPFPop79nrtWvREZC7p+e/o8llNGNWeS8GiZHjDZxaONWhvrZqJKGRu9SNfWH08dxut6gQ9XLZ1+jilAG4KMuEhD/dww7uT+rjVLUrXcKQTMzmMt6+tWlCiVc56rQ6ZZLEqTC0eVq2Ctd2GnKqpRqUbzb1ajp3Y1nqt7M8Nr/XEwTGswt5/kFZpAi7QUz2tW39W4LlPnlzGqx9fkeRxzZ0ws1vkAhB//oJOSh+ao07i3GdneGjydjWlTaqFGUlB+W/Qol/bQpMvI0PlTiGEKqRLsoqXTVyq+8yuLtFRj+C74Bbg6/heKmHhF4lRNZXbeYbQ1Z2yVhxr3i81+DTjT02+EExvJ//96iO08KJmPnjVxxFCY5DC16YMDzGZ04s1MR+Fe3CohWKkgigfnAsZukmyFpZT/Qc9MvRUEDX4/7hEptedUULs/TaQP7yMoDf1V2c7F3jDDqB5Fjkgedqmh2LRJ2YGSFl7ciJ9hpSOCg3FibOOxDX3RPMqUpxUbd9cNyYXykPBwTg2vAe6aFuRf0lahwR6b6hRp4Kbs5sFmpFcQrJjSS9ty1TbriVoeG7MEwmhLRo7L1FYXkcSHngwooxcziU1IntwWoJMhfUZ8cx+dw=

  - stage: conda_package
    install:
      - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      - bash miniconda.sh -b -p $HOME/miniconda
      - export PATH="$HOME/miniconda/bin:$PATH"
      - conda config --set always_yes yes --set changeps1 no
      - conda update conda
      - conda install anaconda-client conda-build
    script:
      - conda build conda.recipe/
      - anaconda --token $CONDA_UPLOAD_TOKEN upload --user pyviz --label dev --label main `conda build --output conda.recipe`

